# Generated by Django 4.0.3 on 2022-04-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisines_category',
            name='desp',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cuisines_category',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuisines_category',
            name='path',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
