# Generated by Django 4.0.3 on 2022-04-10 13:21

from django.db import migrations, models
import phome.models


class Migration(migrations.Migration):

    dependencies = [
        ('phome', '0002_cuisines_category_desp_cuisines_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisines_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=phome.models.filepath),
        ),
    ]
