# Generated by Django 4.0.3 on 2022-04-10 14:02

from django.db import migrations, models
import phome.models


class Migration(migrations.Migration):

    dependencies = [
        ('phome', '0003_cuisines_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisines_category',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=phome.models.filepath),
        ),
    ]
