# Generated by Django 4.0.3 on 2022-04-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phome', '0004_alter_cuisines_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisines_category',
            name='path',
        ),
    ]
